# Generated by Django 6.0.6 on 2026-06-19 17:21

import django.core.validators
import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_username_register_frist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=20, validators=[userapp.models.strong_pass]),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain  10 digitsonly', regex='^{10}$')]),
        ),
    ]
