# Generated by Django 6.0.6 on 2026-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_username_register_frist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
